### PR TITLE
feat: new homepage feature cards

### PR DESCRIPTION
**Pull request by andrepg**
This is my first contribution to the project, to understand how I'll fit and how the project will work out. 

## Introduction

This PR creates 4 new cards to our homepage, providing some copy to invite user to try out our tool. It's a first draft and more improvements will be added later, such as first instructions to build and more information below.

### CODE REVIEW

**Review by devmozao — APPROVED** [review]
lgtm 🚀

**Comment by raisiqueira** [comment]
@andrepg Thanks for this contribution :rocket:. 

I'll (or @luigieai will) set up an environment to deploy the website, also provide a preview of each merge request to make the review easier.

**Comment by andrepg** [comment]
@raisiqueira I think that, to production environment, the GitHub Pages Action will quite fit our need to build and deploy a simple website. Then, if we want a custom domain, just use a CNAME.

**Comment by luigieai** [comment]
@andrepg For production deploy, you are right, we can easily deploy in prod with github pages

@raisiqueira For merge request preview, I only know vercel that easily allow this (I admit that I'm thinking how to self host a system like this using the power of pipelines 👀 Without vendor lock for this). Maybe create an issue so we can work at this (and I don't forget it xD)

**Pull request merged**
